import * as dsa from './dsa/dsa.js';
console.log("En ello!");
console.log('testing queue');
let queue = new dsa.Queue(6);
let stack = new dsa.Stack(6);
console.log(queue);
queue.enqueue(1);
console.log(queue);
queue.enqueue(2);
console.log(queue);
queue.enqueue(3);
console.log(queue);
queue.enqueue(4);
console.log(queue);
queue.enqueue(5);
console.log(queue);
console.log(queue.dequeue());
console.log(queue);
console.log(queue.dequeue());
console.log(queue);
console.log(queue.dequeue());
console.log(queue);
console.log(queue.dequeue());
console.log(queue);
console.log(queue.dequeue());
console.log(queue);
console.log('-------');
console.log(stack);
console.log(stack.push(1));
console.log(stack);
stack.push(2);
console.log(stack);
stack.push(3);
console.log(stack);
stack.push(4);
console.log(stack);
stack.push(5);
console.log(stack);
